source "http://rubygems.org"
gem "rack", "1.3.6"
gem "sinatra"
gem "sequel"
gem "sinatra-sequel"
gem "sqlite3"
gem "rack-flash"
gem "highline"
gem "sinatra-reloader"
gem "bcrypt-ruby"
gem "json"
gem "warden"
